bimeister/pupakit

.github/workflows/release-package-dev.yaml, .github/workflows/release-package-next.yaml, .github/workflows/release-package.yaml, .github/workflows/run-checks.yaml, .moon/project.yml, .moon/toolchain.yml, .moon/workspace.yml, .npmrc, package-lock.json, package.json, projects/common/README.md, projects/common/moon.yml, projects/demo/README.md, projects/demo/src/app/common/components/navbar/components/navbar/navbar.component.ts, projects/forms/README.md, projects/icons/README.md, projects/kit/README.md, projects/overlays/README.md, projects/table/README.md, projects/tree/README.md, projects/widgets/README.md
- Update moon
- Stable local builds
- Add release workflows
- Stable run checks workflow
- Add moon report from moon ci build
=> build: add ci/cd workflows

package-lock.json, projects/icons/src/declarations/constants/icons/app-triangle-left-icon.const.ts, projects/icons/src/declarations/constants/icons/app-triangle-right-icon.const.ts
Related to https://jira.bimeister.io/browse/BIM-28006 (MR https://git.bimeister.io/bimeister/bimeister/-/merge_requests/8221)
=> feature: add left and right triangle icon

package-lock.json, projects/icons/src/declarations/constants/icons/m-window-list.const.ts
Related to [BIM-30550](https://git.bimeister.io/bimeister/bimeister/-/merge_requests/8238)
=> feature: add window list icon

projects/forms/src/components/input/components/input-password/input-password.component.scss
Related to https://jira.bimeister.io/browse/BIM-24841 (MR https://git.bimeister.io/bimeister/bimeister/-/merge_requests/8327)
edge browser bug fix
=> fix: BIM-24841 two eyes password input fix for edge browser

package-lock.json, projects/forms/src/components/input/input.styles.scss
**[Bimeister MR](https://git.bimeister.io/bimeister/bimeister/-/merge_requests/8527)**
=> fix: BIM-25344 Inputs height issue has been resolved.

projects/forms/src/declarations/classes/abstract/input-date-time-base.abstract.ts
https://jira.bimeister.io/browse/BIM-27852
=> fix: BIM-27852

projects/table/src/declarations/classes/table-body-rows-data-source.class.ts
Fix bug, when virtual scroll did not load data after reinitialize pupa-table.
=> fix: BIM-29408 Fixed subscription after reconnect

projects/forms/src/declarations/classes/abstract/input-date-time-base.abstract.ts
Related to [BIM-31681](https://jira.bimeister.io/browse/BIM-31681)
=> fix: BIM-31681 dateIsNotAvailable func update

projects/common/src/styles/mixins/flex-container.mixin.scss, projects/demo/src/app/pages/status-demo/examples/example-2/example-2.component.html, projects/demo/src/app/pages/status-demo/examples/example-3/example-3.component.html, projects/demo/src/app/pages/status-demo/examples/example-3/example-3.component.scss, projects/demo/src/app/pages/status-demo/examples/example-3/example-3.component.ts, projects/demo/src/app/pages/status-demo/examples/example-4/example-4.component.html, projects/demo/src/app/pages/status-demo/examples/example-4/example-4.component.scss, projects/demo/src/app/pages/status-demo/examples/example-4/example-4.component.ts, projects/demo/src/app/pages/status-demo/status-demo.component.html, projects/demo/src/app/pages/status-demo/status-demo.component.scss, projects/demo/src/app/pages/status-demo/status-demo.component.ts, projects/demo/src/app/pages/status-demo/status-demo.module.ts, projects/kit/src/components/status/components/status/status.component.scss, projects/kit/src/declarations/types/status-kind.type.ts
Связанный мердж в bimeister [https://git.bimeister.io/bimeister/bimeister/-/merge_requests/9148](https://git.bimeister.io/bimeister/bimeister/-/merge_requests/9148)
=> feature: BIM-33341 Square kind, marker position

projects/kit/src/components/layout/components/layout/layout.component.html, projects/kit/src/components/layout/components/layout/layout.component.scss, projects/kit/src/components/layout/components/layout/layout.component.ts, projects/kit/src/services/loader.service.ts
1. adds the ability to specify the loader offset
2. adds the ability to specify the layouts direction
=> feature: BIM-34207 Add layout direction

projects/dnd/src/components/dnd-host/dnd-host.component.ts, projects/dnd/src/services/dnd.service.ts
BIM https://git.bimeister.io/bimeister/bimeister/-/merge_requests/10687
=> fix: BIM-36756

projects/demo/src/app/pages/tree-node-demo/examples/example-4/example-4.component.html, projects/demo/src/app/pages/tree-node-demo/examples/example-4/example-4.component.scss, projects/demo/src/app/pages/tree-node-demo/examples/example-4/example-4.component.ts, projects/demo/src/app/pages/tree-node-demo/tree-node-demo.component.html, projects/demo/src/app/pages/tree-node-demo/tree-node-demo.component.ts, projects/demo/src/app/pages/tree-node-demo/tree-node-demo.module.ts, projects/tree/src/components/tree-layout/components/tree-node-description/tree-node-description.component.html, projects/tree/src/components/tree-layout/components/tree-node-description/tree-node-description.component.scss, projects/tree/src/components/tree-layout/components/tree-node-description/tree-node-description.component.ts, projects/tree/src/components/tree-layout/components/tree-node-title/tree-node-title.component.html, projects/tree/src/components/tree-layout/components/tree-node-title/tree-node-title.component.scss, projects/tree/src/components/tree-layout/components/tree-node-title/tree-node-title.component.ts, projects/tree/src/components/tree-layout/components/tree-node/tree-node.component.html, projects/tree/src/components/tree-layout/components/tree-node/tree-node.component.scss, projects/tree/src/components/tree-layout/tree-layout.module.ts
[Задача](https://jira.bimeister.io/browse/BIM-39165)
[Дизайн](https://www.figma.com/file/NMhyHA6sBVIRYR2f1HI7Ya/BIM-37081.-%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%B0-%D0%B2-%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%B5?type=design&node-id=1951-125175&mode=design&t=rhZQPwVc5X0YbIOv-4)
[BIM](https://git.bimeister.io/bimeister/bimeister/-/merge_requests/10844)
=> feature: BIM-39165

projects/forms/src/components/select/components/select-dropdown/select-dropdown.component.scss, projects/kit/src/components/dropdown/components/dropdown-container/dropdown-container.component.scss, projects/kit/src/components/dropdown/components/dropdown-template/dropdown-template.component.scss, projects/overlays/src/components/drawer/components/drawer-layout/drawer-layout.component.scss, projects/overlays/src/components/popover/components/popover-layout/popover-layout.component.scss
В рамках данного мр-а были добавлены тени к Drawer, Popover, Dropdown, Dropdown Menu.
=> feature: BIM-37305

projects/common/src/directives/highlight.directive.ts, projects/common/src/styles/highlight.scss, projects/common/src/types/highlight-kind.type.ts
Related to [BIM-42446](https://jira.bimeister.io/browse/BIM-42446)
=> feature: BIM-42446 highlight tree-node support

projects/demo/src/app/pages/avatar-demo/avatar-demo.component.html, projects/demo/src/app/pages/avatar-demo/avatar-demo.component.ts, projects/demo/src/app/pages/avatar-demo/avatar-demo.module.ts, projects/demo/src/app/pages/avatar-demo/examples/demo-avatar-background-seed-example/demo-avatar-background-seed-example.component.html, projects/demo/src/app/pages/avatar-demo/examples/demo-avatar-background-seed-example/demo-avatar-background-seed-example.component.scss, projects/demo/src/app/pages/avatar-demo/examples/demo-avatar-background-seed-example/demo-avatar-background-seed-example.component.ts, projects/demo/src/app/pages/avatar-demo/examples/example-4/example-4.component.html, projects/kit/src/components/avatar/components/avatar/avatar.component.html, projects/kit/src/components/avatar/components/avatar/avatar.component.scss, projects/kit/src/components/avatar/components/avatar/avatar.component.ts
https://git.bimeister.io/bimeister/bimeister/-/merge_requests/12016
=> feature: BIM-43129 update avatar style

projects/forms/src/components/input/components/input-time/input-time.component.scss, projects/forms/src/components/input/input-date-time.styles.scss
https://git.bimeister.io/bimeister/bimeister/-/merge_requests/12133
=> feature: BIM-43141 remove date & time placeholder on no focus

projects/dnd/src/components/dnd-host/dnd-host.component.ts, projects/table/src/components/system/table/table.component.ts
https://git.bimeister.io/bimeister/bimeister/-/merge_requests/12248
=> feature: BIM-41348 add cssProps config

projects/kit/src/components/tooltip/components/tooltip-content/tooltip-content.component.html, projects/kit/src/components/tooltip/components/tooltip-content/tooltip-content.component.scss
Related to [BIM-44283](https://jira.bimeister.io/browse/BIM-44283)
=> refactor: BIM-44283 tooltip-content style update

projects/demo/src/app/app-routing.module.ts, projects/demo/src/app/common/components/sidebar/sidebar.component.ts, projects/demo/src/app/pages/divider-demo/divider-demo-routing.module.ts, projects/demo/src/app/pages/divider-demo/divider-demo.component.html, projects/demo/src/app/pages/divider-demo/divider-demo.component.scss, projects/demo/src/app/pages/divider-demo/divider-demo.component.ts, projects/demo/src/app/pages/divider-demo/divider-demo.module.ts, projects/demo/src/app/pages/divider-demo/examples/basic-example/basic-example.component.html, projects/demo/src/app/pages/divider-demo/examples/basic-example/basic-example.component.scss, projects/demo/src/app/pages/divider-demo/examples/basic-example/basic-example.component.ts, projects/kit/src/components/divider/components/divider/divider.component.html, projects/kit/src/components/divider/components/divider/divider.component.scss, projects/kit/src/components/divider/components/divider/divider.component.ts, projects/kit/src/components/divider/divider.module.ts, projects/kit/src/components/divider/services/divider.service.ts, projects/kit/src/declarations/types/divider-orientation.type.ts, projects/kit/src/kit.module.ts
https://git.bimeister.io/bimeister/bimeister/-/merge_requests/12461
=> feature: BIM-40264 add divider component

projects/tree/src/declarations/constants/tree-node-offset.const.ts
https://jira.bimeister.io/browse/BIM-42401
=> chore: BIM-42401 change margins in pupa-tree-node

projects/kit/src/components/card/components/card/card.component.scss, projects/kit/src/declarations/types/card-size.type.ts
=> fix: BIM-46317 add auto height

projects/table/src/components/system/table/table.component.html, projects/table/src/components/system/table/table.component.scss, projects/table/src/components/system/table/table.component.ts
Fixes related to https://jira.bimeister.io/browse/BIM-44447
MR in BIM: https://git.bimeister.io/bimeister/bimeister/-/merge_requests/12827
=> fix: BIM-44447 update table

package-lock.json, projects/forms/package.json, projects/forms/src/components/input/components/input-number/input-number.component.html, projects/forms/src/components/input/components/input-number/input-number.component.ts, projects/forms/src/components/input/input.module.ts, projects/forms/src/declarations/classes/abstract/input-base-control-value-accessor.abstract.ts
https://jira.bimeister.io/browse/BIM-26561
При вводе числового значения, а затем символа ".", сбрасывается значение инпута.
=> BIM-26561 fixed wrong behaviour in input number

projects/demo/src/app/pages/textarea-demo/textarea-demo.component.html, projects/demo/src/app/pages/textarea-demo/textarea-demo.component.scss, projects/demo/src/app/pages/textarea-demo/textarea-demo.component.ts, projects/demo/src/app/pages/textarea-demo/textarea-demo.module.ts, projects/demo/src/app/shared/components/example-viewer/components/props-form-control-validators/props-form-control-validators.component.ts
Добавлена вкладка API для textarea
=> feature: BIM-17733 updated textarea page

package-lock.json, projects/demo/src/app/pages/textarea-demo/examples/example-9/example-9.component.html, projects/demo/src/app/pages/textarea-demo/examples/example-9/example-9.component.scss, projects/demo/src/app/pages/textarea-demo/examples/example-9/example-9.component.ts, projects/demo/src/app/pages/textarea-demo/textarea-demo.component.html, projects/demo/src/app/pages/textarea-demo/textarea-demo.component.ts, projects/demo/src/app/pages/textarea-demo/textarea-demo.module.ts, projects/forms/src/components/textarea/components/textarea-inline/textarea-inline.component.html, projects/forms/src/components/textarea/components/textarea-inline/textarea-inline.component.scss, projects/forms/src/components/textarea/components/textarea/textarea.component.html, projects/forms/src/components/textarea/textarea.module.ts, projects/forms/src/components/textarea/textarea.styles.scss, projects/forms/src/declarations/classes/abstract/textarea-base.abstract.ts
В рамках данной задачи для Textarea добавлен вывод ошибки в виде иконки и тултипа при наведении на неё.
=> feature: BIM-47456 added error display with tooltip for text-areas

projects/table/src/components/system/table/table.component.html, projects/table/src/components/system/table/table.component.ts
MR in BIM: https://git.bimeister.io/bimeister/bimeister/-/merge_requests/14001
=> feature: BIM-47561 fix table trackBy functionality

projects/demo/src/app/pages/highlight-demo/examples/example-1/example-1.component.ts, projects/demo/src/app/pages/resizer-demo/examples/example-1/example-1.component.ts, projects/demo/src/app/pages/resizer-demo/examples/example-2/example-2.component.ts, projects/demo/src/app/pages/table-demo/examples/example-1/example-1.component.ts, projects/demo/src/app/pages/table-demo/examples/example-10/example-10.component.ts, projects/demo/src/app/pages/table-demo/examples/example-2/example-2.component.ts, projects/demo/src/app/pages/table-demo/examples/example-3/example-3.component.ts, projects/demo/src/app/pages/table-demo/examples/example-4/example-4.component.ts, projects/demo/src/app/pages/table-demo/examples/example-5/example-5.component.ts, projects/demo/src/app/pages/table-demo/examples/example-6/example-6.component.ts, projects/demo/src/app/pages/table-demo/examples/example-7/example-7.component.ts, projects/demo/src/app/pages/table-demo/examples/example-8/example-8.component.ts, projects/demo/src/app/pages/table-demo/examples/example-9/example-9.component.ts, projects/table/src/components/system/table/table.component.html, projects/table/src/components/system/table/table.component.ts, projects/table/src/declarations/classes/table-controller.class.ts, projects/table/src/declarations/classes/table-data-display-collection.class.ts, projects/table/src/declarations/interfaces/table-controller-options.interface.ts
MR in BIM: https://git.bimeister.io/bimeister/bimeister/-/merge_requests/14095
=> feature: BIM-51576 fix table trackBy

projects/table/src/components/system/table-body-row-container/table-body-row-container.component.html, projects/table/src/pipes/serialize-table-body-row.pipe.ts, projects/table/src/table.module.ts
BIM: https://git.bimeister.io/bimeister/bimeister/-/merge_requests/14157
=> feature: BIM-51746 add json data attribute to table cell

projects/demo/src/app/pages/button-group-demo/button-group-demo.component.html, projects/demo/src/app/pages/button-group-demo/button-group-demo.component.ts, projects/demo/src/app/pages/button-group-demo/button-group-demo.module.ts, projects/demo/src/app/pages/button-group-demo/examples/example-6/example-6.component.html, projects/demo/src/app/pages/button-group-demo/examples/example-6/example-6.component.scss, projects/demo/src/app/pages/button-group-demo/examples/example-6/example-6.component.ts, projects/demo/src/app/pages/stepper-demo/examples/example-6/example-6.component.html, projects/demo/src/app/pages/stepper-demo/examples/example-6/example-6.component.scss, projects/demo/src/app/pages/stepper-demo/examples/example-6/example-6.component.ts, projects/demo/src/app/pages/stepper-demo/stepper-demo.component.html, projects/demo/src/app/pages/stepper-demo/stepper-demo.component.ts, projects/demo/src/app/pages/stepper-demo/stepper-demo.module.ts, projects/demo/src/app/pages/tabs-demo/examples/example-8/example-8.component.html, projects/demo/src/app/pages/tabs-demo/examples/example-8/example-8.component.scss, projects/demo/src/app/pages/tabs-demo/examples/example-8/example-8.component.ts, projects/demo/src/app/pages/tabs-demo/tabs-demo.component.html, projects/demo/src/app/pages/tabs-demo/tabs-demo.component.ts, projects/demo/src/app/pages/tabs-demo/tabs-demo.module.ts, projects/kit/src/components/button-group/components/button-group-item/button-group-item.component.ts, projects/kit/src/components/stepper/components/stepper-item/stepper-item.component.ts, projects/kit/src/components/tabs/components/tabs-item/tabs-item.component.ts, projects/kit/src/declarations/classes/abstract/tabs-item-base.abstract.ts
Задача на изменение tabs, group button, stepper компонентов:
https://jira.bimeister.io/browse/BIM-49128
Баг, где решение задачи сводится к изменению компонентов в pupakit: 
https://jira.bimeister.io/browse/BIM-37371
Связанный MR: https://git.bimeister.io/bimeister/bimeister/-/merge_requests/14049
=> feature: BIM-49128 add clickEvent to tabsItemBase

projects/demo/src/app/pages/input-demo/examples/input-demo-example-all-inputs/input-demo-example-all-inputs.component.html, projects/demo/src/app/pages/input-demo/examples/input-demo-example-all-inputs/input-demo-example-all-inputs.component.scss, projects/demo/src/app/pages/input-demo/input-demo.component.html, projects/demo/src/app/pages/input-demo/input-demo.component.ts, projects/forms/src/components/input/components/input-text/input-text.component.html, projects/forms/src/components/input/input.module.ts, projects/forms/src/components/input/input.styles.scss, projects/forms/src/declarations/classes/abstract/input-base.abstract.ts
https://github.com/user-attachments/assets/3c37376a-6a78-4bcc-87fa-45eb6f66249d
=> feature: BIM-52797 add loading input to InputBase
